### ISSUE TITLE
Add step-by-step documentation

### ISSUE THREAD

**Issue by sathieu** [lemonldap-ng-controller/lemonldap-ng-controller#27]
How to install from scratch.

**Comment by sathieu** [comment]
/etc/lemonldap-ng/nginx-lmlog.conf 
```
log_format lm_combined '$remote_addr - $lmremote_user [$time_local] '
	'"$request" $status $body_bytes_sent '
	'"$http_referer" "$http_user_agent"';
```

/etc/lemonldap-ng/nginx-lua-headers.conf 
```
    auth_request_set $headername1 $upstream_http_headername1;
    auth_request_set $headervalue1 $upstream_http_headervalue1;
    auth_request_set $headername2 $upstream_http_headername2;
    auth_request_set $headervalue2 $upstream_http_headervalue2;
    auth_request_set $headername3 $upstream_http_headername3;
    auth_request_set $headervalue3 $upstream_http_headervalue3;
    auth_request_set $headername4 $upstream_http_headername4;
    auth_request_set $headervalue4 $upstream_http_headervalue4;
    auth_request_set $headername5 $upstream_http_headername5;
    auth_request_set $headervalue5 $upstream_http_headervalue5;
    auth_request_set $headername6 $upstream_http_headername6;
    auth_request_set $headervalue6 $upstream_http_headervalue6;
    auth_request_set $headername7 $upstream_http_headername7;
    auth_request_set $headervalue7 $upstream_http_headervalue7;
    auth_request_set $headername8 $upstream_http_headername8;
    auth_request_set $headervalue8 $upstream_http_headervalue8;
    auth_request_set $headername9 $upstream_http_headername9;
    auth_request_set $headervalue9 $upstream_http_headervalue9;
    auth_request_set $headername10 $upstream_http_headername10;
    auth_request_set $headervalue10 $upstream_http_headervalue10;
    auth_request_set $lmcookie $upstream_http_cookie;
    access_by_lua '
      i = 1
      ngx.req.set_header("Cookie",ngx.var.lmcookie)
      while true do
        if ngx.var["headername"..i] ~= nil then
          ngx.req.set_header(ngx.var["headername"..i],ngx.var["headervalue"..i])
        else
          break
        end
        i = i +1
      end
    ';

```

**Comment by sathieu** [comment]
http-snipset:
```
include /etc/lemonldap-ng/nginx-lmlog.conf;
```

server-snipset:
```
  location = /lmauth {
    internal;
    include /etc/nginx/fastcgi_params;
    fastcgi_pass unix:/var/run/llng-fastcgi-server/llng-fastcgi.sock;
    # To use AuthBasic handler, uncomment this and remove "error_page 401"
    # fastcgi_param LLTYPE authbasic;

    # Drop post datas
    fastcgi_pass_request_body  off;
    fastcgi_param CONTENT_LENGTH "";

    # Keep original hostname
    fastcgi_param HOST $http_host;

    # Keep original request (LLNG server will received /llauth)
    fastcgi_param X_ORIGINAL_URI  $request_uri;
  }
```

```
  location / {
    # Local application
    index index.pl;
    try_files $uri $uri/ =404;

    # Reverse proxy
    #proxy_pass http://remote.server/;
    #include /etc/nginx/proxy_params;

    ##################################
    # CALLING AUTHENTICATION         #
    ##################################
    auth_request /lmauth;
    auth_request_set $lmremote_user $upstream_http_lm_remote_user;
    auth_request_set $lmlocation $upstream_http_location;
    # Uncomment this if CDA is used
    #auth_request_set $cookie_value $upstream_http_set_cookie;
    #add_header Set-Cookie $cookie_value;
    # Remove this for AuthBasic handler
    error_page 401 $lmlocation;

    ##################################
    # PASSING HEADERS TO APPLICATION #
    ##################################

    # IF LUA IS SUPPORTED
    #include /etc/lemonldap-ng/nginx-lua-headers.conf;

    # ELSE
    # Set manually your headers
    #auth_request_set $authuser $upstream_http_auth_user;
    #proxy_set_header Auth-User $authuser;
    # OR in the correspondinc block
    #fastcgi_param HTTP_AUTH_USER $authuser;

    # Then (if LUA not supported), change cookie header to hide LLNG cookie
    #auth_request_set $lmcookie $upstream_http_cookie;
    #proxy_set_header Cookie: $lmcookie;
    # OR in the corresponding block
    #fastcgi_param HTTP_COOKIE $lmcookie;

    # Uncomment this if you use https only
    #add_header Strict-Transport-Security "15768000";

    # Set REMOTE_USER (for FastCGI apps only)
    #fastcgi_param REMOTE_USER $lmremote_user;
  }
```

**Comment by sathieu** [comment]
Proposal:
```yaml
apiVersion: v1
kind: ConfigMap
data:
  http-snippet: |
    log_format lm_combined '$remote_addr - $lmremote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';
  server-snippet: |
    location = /lmauth {
      internal;
      include /etc/nginx/fastcgi_params;
      fastcgi_pass localhost:9000;
      # To use AuthBasic handler, uncomment this and remove "error_page 401"
      # fastcgi_param LLTYPE authbasic;

      # Drop post datas
      fastcgi_pass_request_body  off;
      fastcgi_param CONTENT_LENGTH "";

      # Keep original hostname
      fastcgi_param HOST $http_host;

      # Keep original request (LLNG server will received /llauth)
      fastcgi_param X_ORIGINAL_URI  $request_uri;
    }
  location-snippet: |
    ##################################
    # CALLING AUTHENTICATION         #
    ##################################
    auth_request /lmauth;
    auth_request_set $lmremote_user $upstream_http_lm_remote_user;
    auth_request_set $lmlocation $upstream_http_location;
    # Uncomment this if CDA is used
    #auth_request_set $cookie_value $upstream_http_set_cookie;
    #add_header Set-Cookie $cookie_value;
    # Remove this for AuthBasic handler
    error_page 401 $lmlocation;

    ##################################
    # PASSING HEADERS TO APPLICATION #
    ##################################
    auth_request_set $authuser $upstream_http_auth_user;
    proxy_set_header Auth-User $authuser;

    # Change cookie header to hide LLNG cookie
    auth_request_set $lmcookie $upstream_http_cookie;
    proxy_set_header Cookie: $lmcookie;
```
