### ISSUE TITLE
Change the ConfigMap

### ISSUE THREAD

**Issue by sathieu** [lemonldap-ng-controller/lemonldap-ng-controller#56]
Currently:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: lemonldap-ng-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  lmConf.js: |
    # SSO Cookie
    domain: example.org
    cookieName: lemonldap
    securedCookie: 0 # 0=unsecuredCookie, 1=securedCookie, 2=doubleCookie, 3=doubleCookieForSingleSession
```
Wanted:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: lemonldap-ng-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  # SSO Cookie
  domain: example.org
  cookieName: lemonldap
  securedCookie: 0 # 0=unsecuredCookie, 1=securedCookie, 2=doubleCookie, 3=doubleCookieForSingleSession
```

Rationale: the level 1 configs are easier to modify using the k8s API.
